### ISSUE TITLE
Mobile View

### ISSUE THREAD

**Issue by harshkhandeparkar** [metakgp/societytable#1]
The societytable in its current form does not render on mobile screens. It would be good to make it responsive.

**Comment by harshkhandeparkar** [comment]
The current plan:
- Use a modal instead of a tooltip and open it on hover instead of on click.
- On mobile, make the table scrollable and/or a bit smaller.

**Comment by SachdevJai** [comment]
hi @harshkhandeparkar I'd like to work on this, can you assign this issue to me?

**Comment by harshkhandeparkar** [comment]
Welcome @SachdevJai and thanks for showing interest in working on this! Assigned.
